// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: test2.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Student2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *Student2) Reset() {
	*x = Student2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Student2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student2) ProtoMessage() {}

func (x *Student2) ProtoReflect() protoreflect.Message {
	mi := &file_test2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student2.ProtoReflect.Descriptor instead.
func (*Student2) Descriptor() ([]byte, []int) {
	return file_test2_proto_rawDescGZIP(), []int{0}
}

func (x *Student2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student2) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type Class2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassName string `protobuf:"bytes,1,opt,name=className,proto3" json:"className,omitempty"`
}

func (x *Class2) Reset() {
	*x = Class2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Class2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Class2) ProtoMessage() {}

func (x *Class2) ProtoReflect() protoreflect.Message {
	mi := &file_test2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Class2.ProtoReflect.Descriptor instead.
func (*Class2) Descriptor() ([]byte, []int) {
	return file_test2_proto_rawDescGZIP(), []int{1}
}

func (x *Class2) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

var File_test2_proto protoreflect.FileDescriptor

var file_test2_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x65, 0x73, 0x74, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x30, 0x0a, 0x08, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x32, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x61, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x06, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x32, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x34, 0x0a, 0x0a, 0x46,
	0x69, 0x6e, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x32, 0x12, 0x26, 0x0a, 0x08, 0x4d, 0x79, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x32, 0x12, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x32, 0x1a, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x32, 0x22,
	0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x73, 0x2f, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test2_proto_rawDescOnce sync.Once
	file_test2_proto_rawDescData = file_test2_proto_rawDesc
)

func file_test2_proto_rawDescGZIP() []byte {
	file_test2_proto_rawDescOnce.Do(func() {
		file_test2_proto_rawDescData = protoimpl.X.CompressGZIP(file_test2_proto_rawDescData)
	})
	return file_test2_proto_rawDescData
}

var file_test2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test2_proto_goTypes = []interface{}{
	(*Student2)(nil), // 0: pb.Student2
	(*Class2)(nil),   // 1: pb.Class2
}
var file_test2_proto_depIdxs = []int32{
	0, // 0: pb.FindClass2.MyClass2:input_type -> pb.Student2
	1, // 1: pb.FindClass2.MyClass2:output_type -> pb.Class2
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test2_proto_init() }
func file_test2_proto_init() {
	if File_test2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Student2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Class2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test2_proto_goTypes,
		DependencyIndexes: file_test2_proto_depIdxs,
		MessageInfos:      file_test2_proto_msgTypes,
	}.Build()
	File_test2_proto = out.File
	file_test2_proto_rawDesc = nil
	file_test2_proto_goTypes = nil
	file_test2_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FindClass2Client is the client API for FindClass2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FindClass2Client interface {
	MyClass2(ctx context.Context, in *Student2, opts ...grpc.CallOption) (*Class2, error)
}

type findClass2Client struct {
	cc grpc.ClientConnInterface
}

func NewFindClass2Client(cc grpc.ClientConnInterface) FindClass2Client {
	return &findClass2Client{cc}
}

func (c *findClass2Client) MyClass2(ctx context.Context, in *Student2, opts ...grpc.CallOption) (*Class2, error) {
	out := new(Class2)
	err := c.cc.Invoke(ctx, "/pb.FindClass2/MyClass2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FindClass2Server is the server API for FindClass2 service.
type FindClass2Server interface {
	MyClass2(context.Context, *Student2) (*Class2, error)
}

// UnimplementedFindClass2Server can be embedded to have forward compatible implementations.
type UnimplementedFindClass2Server struct {
}

func (*UnimplementedFindClass2Server) MyClass2(context.Context, *Student2) (*Class2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MyClass2 not implemented")
}

func RegisterFindClass2Server(s *grpc.Server, srv FindClass2Server) {
	s.RegisterService(&_FindClass2_serviceDesc, srv)
}

func _FindClass2_MyClass2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Student2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindClass2Server).MyClass2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FindClass2/MyClass2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindClass2Server).MyClass2(ctx, req.(*Student2))
	}
	return interceptor(ctx, in, info, handler)
}

var _FindClass2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FindClass2",
	HandlerType: (*FindClass2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MyClass2",
			Handler:    _FindClass2_MyClass2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test2.proto",
}
